# Generated by Django 6.0.5 on 2026-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'кот'), ('F', 'кошка')], max_length=1)),
                ('color', models.CharField(choices=[('black', 'черный'), ('colored', 'цветной')], max_length=10)),
            ],
        ),
    ]
